version: "3.9"

services:
  api: &api
    build:
      context: .
      dockerfile: docker/dev/Dockerfile
    image: ray_slack_integration
    command: uvicorn main:app --host 0.0.0.0 --reload
    volumes:
      - .:/app
    ports:
      - 8008:8000
    env_file:
      - ./.env
    restart: unless-stopped
